services:
  - elasticsearch
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
env:
  # different connection classes to test
  - TEST_ES_CONNECTION=Urllib3HttpConnection
  - TEST_ES_CONNECTION=RequestsHttpConnection
matrix:
  exclude:
    # skip testing thrift on py3
    - python: "3.3"
      env: TEST_ES_CONNECTION=ThriftConnection
install:
  - git submodule init
  - pip install coveralls
  - pip install .
script:
  - TEST_ES_SERVER=localhost python setup.py test
after_success:
  - coveralls
