language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
install:
  - pip install -r dev_requirements.txt --use-mirrors
  - python setup.py develop
script:
  - python setup.py test
  - python setup.py build_sphinx -b doctest
